-- ORDER BY

SELECT coluna1,coluna2
FROM tabela
ORDER BY coluna1 asc/desc


-- WITH TIES

SELECT TOP(3) WITH TIES NOME_TIME,  PONTOS
FROM tbl_times
ORDER BY Pontos DESC

O WITH TIES ESTÁ FAZENDO COM QUE MOSTRE OS 3 PRIMEIROS TIMES EM RELAÇÃO A SUA PONTUAÇÃO,OU SEJA, SE TIVER MAIS DE 3 TIMES QUE ATINGIRAM OS 3 MAIORES PONTOS, ELE VAI MOSTRAR TODOS.

POIS OS TIMES PODEM TER A MESMA PONTUAÇÃO