FROM openjdk

RUN mkdir -p /app/aula

ENV APP_NAME=produto.jar

COPY ${APP_NAME} /app/aula/

EXPOSE 8081

# ENTRYPOINT NÃO TRABALHA COM AS VARIÁVEIS DE AMBIENTE
ENTRYPOINT [ "java", "-jar", "/app/aula/produtos.jar" ]