# UMA FUNÇÃO LAMBDA EM PYTHON É UMA FUNÇÃO ANÔNIMA, OU SEJA, UMA FUNÇÃO SEM NOME.
# ELA É A FORMA CONCISA DE DEFINIR UMA FUNÇÃO EM APENAS UMA LINHA DE CÓDIGO.
# AO CONTRÁRIO DAS FUNÇÕES TRADICIONAIS, AS FUNÇÕES LAMBDA NÃO SÃO DEFINIDAS
# COM A PALAVRA-CHAVE "def" E NÃO POSSUEM UM BLOCO DE CÓDIGO SEPARADO.



def soma(a):
    return lambda n: n + a

print(2)