-- VIEW

UMA VIEW NA TERMINOLOGIA SQL É UMA ÚNICA TABELA QUE É DERIVADA DE OUTRAS TABELAS. ESSAS OUTRAS TABELAS PODEM SER TABELAS DA BASE DE DADOS OU OUTRAS VISÕES PREVIAMENTE DEFINIDAS.


UMA VISÃO NÃO NECESSARIAMENTE EXISTE NA FORMA FÍSICA; É CONSIDERADO COMO UMA TABELA VIRTUAL,  AO CONTRÁRIO DAS TABELAS DA BASE DE DADOS, CUJAS TUPLAS SÃO SEMPRE ARMAZENADAS FISICAMENTE NO BANCO DE DADOS.

ISSO LIMMITA POSSÍVEIS OPERAÇÕES DE ATUALIZAÇÃO QUE PODEM SER APLICADAS ÀS VISÕES, MAS NÃO FORNECE NENHUMA LIMITAÇÃO NA CONSULTA DE UMA VISÃO.

ESSA TABELA VIRTUAL, SÓ É CRIADA NO MOMENTO EM QUE É INVOCADA, PARA AQUELE MOMENTO ESPECÍFICO.

PODEMOS PENSAR EM UAM VISÃO COMO UMA FORMA DE DEIXAR PRONTA UMA CONSULTA A UMA OU MAIS TABELAS QUE PRECISAMOS ACESSAR FREQUENTEMENTE, MESMO QUE POSSA NÃO EXISTIR FISICAMENTE.



CREATE VIEW [Pessoas Simplificadas] AS 
SELECT FirstName, MiddleName, LastName
FROM Person.Person
WHERE Title = 'Ms.'

SELECT * FROM [Pessoas Simplificadas]


-- PARA EXCLUIR UMA VIEW

DROP VIEW nomeDaView


-- ALTER VIEW

ALTER VIEW [Pessoas Simplificadas] AS 
SELECT FirstName, MiddleName, LastName, BusinessEntityID
FROM Person.Person
WHERE Title = 'Ms.'