-- CRIE 2 TABELAS NOVAS COM A CONSTRAINT UNIQUE

CREATE TABLE Cliente (
    id INT IDENTITY,
    nome VARCHAR(100) NOT NULL,
    cpf BIGINT UNIQUE NOT NULL,
    idade INT NOT NULL
);

CREATE TABLE Aluno (
    id_aluno INT IDENTITY,
    nome VARCHAR(100) NOT NULL,
    ra int UNIQUE NOT NULL
);